/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-variant': '#d3e4fe',
        'surface-container-low': '#eff4ff',
        'on-tertiary-container': '#3d4042',
        'on-error': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-container-high': '#dce9ff',
        'inverse-primary': '#4ae176',
        'surface-dim': '#cbdbf5',
        'primary-fixed': '#6bff8f',
        'on-secondary-fixed': '#1a1c1c',
        'on-secondary-container': '#616363',
        primary: '#006e2f',
        'on-secondary-fixed-variant': '#454747',
        'on-primary-fixed': '#002109',
        'surface-container': '#e5eeff',
        'surface-bright': '#f8f9ff',
        'tertiary-fixed-dim': '#c4c7c9',
        'on-background': '#0b1c30',
        secondary: '#5d5f5f',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#4ae176',
        'on-primary-fixed-variant': '#005321',
        'on-tertiary-fixed-variant': '#444749',
        'inverse-on-surface': '#eaf1ff',
        'tertiary-fixed': '#e0e3e5',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#191c1e',
        'secondary-fixed': '#e2e2e2',
        'inverse-surface': '#213145',
        'secondary-container': '#dfe0e0',
        error: '#ba1a1a',
        surface: '#f8f9ff',
        background: '#f8f9ff',
        'tertiary-container': '#a9acae',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#c6c6c7',
        'outline-variant': '#bccbb9',
        'on-primary-container': '#004b1e',
        'primary-container': '#22c55e',
        'on-surface-variant': '#3d4a3d',
        'surface-tint': '#006e2f',
        'on-surface': '#0b1c30',
        'surface-container-highest': '#d3e4fe',
        'on-error-container': '#93000a',
        outline: '#6d7b6c',
        tertiary: '#5c5f61',
        // Status colors added for booking / payment states
        warning: '#a15c00',
        'warning-container': '#ffddb0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '8px',
        xl: '12px',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '1rem',
        'stack-sm': '0.5rem',
        'stack-md': '1rem',
        'stack-lg': '2rem',
        'margin-desktop': '2.5rem',
        'container-max': '1280px',
        gutter: '1.5rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
